name: gavatcore_panel
description: "GavatCore Management Panel - Neon Glassmorphic Design"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # UI & Animations
  flutter_animate: ^4.3.0
  glassmorphism: ^3.0.0
  
  # HTTP & API
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # Data Models
  freezed_annotation: ^2.4.1
  
  # Charts & Graphs
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.2.7
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # URL Strategy (Web)
  flutter_web_plugins:
    sdk: flutter
  url_strategy: ^0.2.0
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.9
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: OnlyVips
      fonts:
        - asset: assets/fonts/OnlyVips-Regular.ttf
        - asset: assets/fonts/OnlyVips-Bold.ttf
          weight: 700
