name: gavatcore_mobile
description: "Modern, AI-powered yayıncı & admin yönetim paneli"
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.0
  fl_chart: ^0.62.0
  lottie: ^2.6.0
  shared_preferences: ^2.2.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  intl: ^0.18.1
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  crypto: ^3.0.3
  js: ^0.6.7
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/icons/app_icon_adaptive.png"

flutter_native_splash:
  color: "#1A1A1A"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash_android12.png
    color: "#1A1A1A" 